// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package group

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func GroupResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"code": schema.StringAttribute{
				Optional:            true,
				Description:         "Optional code for use with policies",
				MarkdownDescription: "Optional code for use with policies",
			},
			"id": schema.Int64Attribute{
				Computed:            true,
				Description:         "The ID of the group",
				MarkdownDescription: "The ID of the group",
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"labels": schema.SetAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Description:         "The organization labels associated with the group",
				MarkdownDescription: "The organization labels associated with the group",
			},
			"location": schema.StringAttribute{
				Optional:            true,
				Description:         "Optional location for the group",
				MarkdownDescription: "Optional location for the group",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "A unique name for the group",
				MarkdownDescription: "A unique name for the group",
			},
		},
	}
}

type GroupModel struct {
	Code     types.String `tfsdk:"code"`
	Id       types.Int64  `tfsdk:"id"`
	Labels   types.Set    `tfsdk:"labels"`
	Location types.String `tfsdk:"location"`
	Name     types.String `tfsdk:"name"`
}
