// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package serviceplan

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ServicePlanDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"code": schema.StringAttribute{
				Computed:            true,
				Description:         "The code of the Morpheus service plan",
				MarkdownDescription: "The code of the Morpheus service plan",
			},
			"description": schema.StringAttribute{
				Computed:            true,
				Description:         "The description of the Morpheus service plan",
				MarkdownDescription: "The description of the Morpheus service plan",
			},
			"id": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Morpheus ID of the Object being referenced",
				MarkdownDescription: "Morpheus ID of the Object being referenced",
				Validators: []validator.Int64{
					int64validator.ConflictsWith(path.Expressions{
						path.MatchRoot("name"),
						path.MatchRoot("provision_type_code"),
					}...),
				},
			},
			"name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The name of the Morpheus service plan",
				MarkdownDescription: "The name of the Morpheus service plan",
				Validators: []validator.String{
					stringvalidator.AlsoRequires(path.Expressions{
						path.MatchRoot("provision_type_code"),
					}...),
				},
			},
			"provision_type_code": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The provision type code of the Morpheus service plan",
				MarkdownDescription: "The provision type code of the Morpheus service plan",
				Validators: []validator.String{
					stringvalidator.AlsoRequires(path.Expressions{
						path.MatchRoot("name"),
					}...),
				},
			},
		},
	}
}

type ServicePlanModel struct {
	Code              types.String `tfsdk:"code"`
	Description       types.String `tfsdk:"description"`
	Id                types.Int64  `tfsdk:"id"`
	Name              types.String `tfsdk:"name"`
	ProvisionTypeCode types.String `tfsdk:"provision_type_code"`
}
