// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package role

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func RoleDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"description": schema.StringAttribute{
				Computed: true,
			},
			"id": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Morpheus ID of the Object being referenced",
				MarkdownDescription: "Morpheus ID of the Object being referenced",
				Validators: []validator.Int64{
					int64validator.ConflictsWith(path.Expressions{
						path.MatchRoot("name"),
					}...),
				},
			},
			"landing_url": schema.StringAttribute{
				Computed:            true,
				Description:         "An optional override for the default landing page after login for a user.",
				MarkdownDescription: "An optional override for the default landing page after login for a user.",
			},
			"multitenant": schema.BoolAttribute{
				Computed:            true,
				Description:         "Multitenant roles are copied to all tenant accounts and kept in sync until a sub-tenant user modifies their copy of the role. *Only available to master tenant*",
				MarkdownDescription: "Multitenant roles are copied to all tenant accounts and kept in sync until a sub-tenant user modifies their copy of the role. *Only available to master tenant*",
			},
			"multitenant_locked": schema.BoolAttribute{
				Computed:            true,
				Description:         "Multitenant Locked prevents sub-tenant users from modifying their copy of multitenant roles. *Only available to master tenant*",
				MarkdownDescription: "Multitenant Locked prevents sub-tenant users from modifying their copy of multitenant roles. *Only available to master tenant*",
			},
			"name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The name of the Morpheus role",
				MarkdownDescription: "The name of the Morpheus role",
				Validators: []validator.String{
					stringvalidator.ConflictsWith(path.Expressions{
						path.MatchRoot("id"),
					}...),
				},
			},
			"role_type": schema.StringAttribute{
				Computed:            true,
				Description:         "Role type",
				MarkdownDescription: "Role type",
			},
		},
	}
}

type RoleModel struct {
	Description       types.String `tfsdk:"description"`
	Id                types.Int64  `tfsdk:"id"`
	LandingUrl        types.String `tfsdk:"landing_url"`
	Multitenant       types.Bool   `tfsdk:"multitenant"`
	MultitenantLocked types.Bool   `tfsdk:"multitenant_locked"`
	Name              types.String `tfsdk:"name"`
	RoleType          types.String `tfsdk:"role_type"`
}
