# Copyright 2025 Hewlett Packard Enterprise Development LP

name: Build

on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        go: [ '1.24.1' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go version
      - run: make build
