# Copyright 2025 Hewlett Packard Enterprise Development LP

name: Docs

on:
  push:
    branches:
      - main
  pull_request:
jobs:
  docs:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        go: [ '1.24.1' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2
      - run: go version
      - run: terraform version
      - run: make docs
